name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: unzip PojavModManager.zip -d project

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fix gradle.properties
        run: |
          echo "android.useAndroidX=true" >> project/PojavModManager/gradle.properties
          echo "android.enableJetifier=true" >> project/PojavModManager/gradle.properties

      - name: Setup Gradle
        run: |
          cd project/PojavModManager
          gradle wrapper

      - name: Build APK
        run: |
          cd project/PojavModManager
          chmod +x gradlew
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: "**/*.apk"
